# Generated by Django 4.0.1 on 2022-01-29 02:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exe_intensity', models.IntegerField(blank=True, verbose_name='运动强度')),
                ('completion', models.FloatField(blank=True, verbose_name='完成度')),
                ('action_list', models.CharField(default=[], max_length=100, validators=[django.core.validators.int_list_validator], verbose_name='动作标准度序列')),
                ('coor_list', models.CharField(default=[], max_length=100, validators=[django.core.validators.int_list_validator], verbose_name='协调性序列')),
                ('heart_list', models.CharField(default=[], max_length=100, validators=[django.core.validators.int_list_validator], verbose_name='心率序列')),
                ('cal_list', models.CharField(default=[], max_length=100, validators=[django.core.validators.int_list_validator], verbose_name='卡路里序列')),
                ('perfect_a_path', models.CharField(max_length=500, null=True, verbose_name='高分动作存储路径')),
            ],
            options={
                'verbose_name': '报告',
                'verbose_name_plural': '报告',
                'db_table': 'report',
            },
        ),
    ]
