# Generated by Django 4.0.1 on 2022-01-29 02:57

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ex_record',
            fields=[
                ('record_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='运动记录id')),
                ('finish_time', models.DateTimeField(default=datetime.datetime(2022, 1, 29, 10, 57, 38, 41851), verbose_name='运动结束时间')),
                ('v_chosen', models.CharField(default=[], max_length=100, validators=[django.core.validators.int_list_validator], verbose_name='视频选择序列')),
                ('A_length', models.IntegerField(verbose_name='运动时长')),
                ('poster_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='海报地址')),
                ('report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.report')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record', to='account.user')),
            ],
            options={
                'verbose_name': '运动记录',
                'verbose_name_plural': '运动记录',
                'db_table': 'ex_record',
                'ordering': ['-finish_time'],
            },
        ),
    ]
