# Generated by Django 4.0.1 on 2022-02-04 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ex_record',
            options={'ordering': ['-start_time'], 'verbose_name': '运动记录', 'verbose_name_plural': '运动记录'},
        ),
        migrations.RemoveField(
            model_name='ex_record',
            name='finish_time',
        ),
        migrations.AddField(
            model_name='ex_record',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='是否完成'),
        ),
        migrations.AddField(
            model_name='ex_record',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 4, 16, 21, 28, 34582), verbose_name='运动结束时间'),
        ),
    ]
