# Generated by Django 4.0.1 on 2022-02-04 08:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_emailverifyrecord_send_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_plan', models.CharField(default=[], max_length=100, validators=[django.core.validators.int_list_validator], verbose_name='视频选择序列')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.user')),
            ],
            options={
                'verbose_name': '计划推荐',
                'verbose_name_plural': '计划推荐',
                'db_table': 'plan',
            },
        ),
    ]
