# Generated by Django 4.0.1 on 2022-01-29 02:57

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('send_type', models.CharField(choices=[('register', '注册'), ('forget', '找回密码')], max_length=10, verbose_name='验证码类型')),
                ('send_time', models.DateTimeField(default=datetime.datetime(2022, 1, 29, 10, 57, 38, 37729), verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
                'db_table': 'EmailVerify',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(default='', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='email')),
                ('password', models.CharField(default='', max_length=255)),
                ('nickname', models.CharField(max_length=100, null=True, verbose_name='昵称')),
                ('sex', models.CharField(max_length=3, null=True, verbose_name='性别')),
                ('birth_date', models.DateField(null=True, verbose_name='出生日期')),
                ('weight', models.FloatField(null=True, verbose_name='体重')),
                ('height', models.FloatField(null=True, verbose_name='身高')),
                ('status', models.BooleanField(db_index=True, default=False)),
                ('img_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='头像')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('refind_token', models.CharField(max_length=255, null=True, verbose_name='找回密码令牌')),
                ('prefer_list', models.CharField(default=[0, 0, 0, 0, 0, 0, 0, 0, 0], max_length=100, null=True, validators=[django.core.validators.int_list_validator])),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
    ]
