# Generated by Django 4.0.1 on 2022-02-04 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 4, 16, 21, 28, 32121), verbose_name='发送时间'),
        ),
    ]
