# Generated by Django 4.0.1 on 2022-02-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(null=True)),
                ('commodity_path', models.URLField(max_length=500, verbose_name='商品路径')),
                ('pic_path', models.URLField(max_length=500, verbose_name='缩略图路径')),
                ('introduction', models.TextField(blank=True, max_length=1023, verbose_name='商品简介')),
            ],
            options={
                'verbose_name': '商店',
                'verbose_name_plural': '商店',
                'db_table': 'shop',
            },
        ),
    ]
